#pragma once
#pragma pack(push,1)

#define II_VERSION "1.1.0"  //1.0.0. char version[10];
#define ALL_INTERFACE -1

#define TCP_SERVER_DYNAMIC		0 
#define TCP_SERVER_STATIC		1

#define UDP_UNICAST				0
#define UDP_MULTICAST			1

enum E_INTERFACE_TYPE	//통신 모듈 타입
{
	_UDP_UNICAST = 0,
	_UDP_MULTICAST,
	_TCP_SERVER,
	_TCP_CLIENT,
	_SERIAL,
	MAX
};

enum E_EQUIPMENT_ID		//Config 폴더 내 ini파일 명명 규칙에 쓰이는 enum 값.
{
	EQUIP_ID_OSD = 0,
	EQUIP_ID_MFR = 1,
	EQUIP_ID_SONAR = 2,
	EQUIP_ID_RCWS = 3,
	EQUIP_ID_TACM = 4,
	EQUIP_ID_BCU = 5,
	EQUIP_ID_CIWS2 = 6,
	EQUIP_ID_DECOY = 7,
	EQUIP_ID_EOTS = 8,
	EQUIP_ID_EW2 = 9,
	EQUIP_ID_IFF = 10,
	EQUIP_ID_IRST = 11,
	EQUIP_ID_LESM = 12,
	EQUIP_ID_NR = 13,
	EQUIP_ID_SAAM = 14,
	EQUIP_ID_SAM2 = 15,
	EQUIP_ID_SLM = 16,
	EQUIP_ID_SLTS = 17,
	EQUIP_ID_SSM = 18,
	EQUIP_ID_SSMx = 19,
	EQUIP_ID_TRN = 20,
	EQUIP_ID_VLA = 21,
	EQUIP_ID_ALL
};
 
enum E_CONFIG_STRING_IDX	//설정파일(*.ini)에 사용되는 필드들의 enum값
{
	CSI_START_SECTION,		// CONFIG_STRING[CSI_START_SECTION]	
	CSI_IF_ID,				// CONFIG_STRING[CSI_IF_ID]			
	CSI_IF_TYPE,			// CONFIG_STRING[CSI_IF_TYPE]			
	CSI_IF_DESCRIPTION,		// CONFIG_STRING[CSI_IF_DESCRIPTION]	
	CSI_ETHERNET_SECTION,	// CONFIG_STRING[CSI_ETHERNET_SECTION] 
	CSI_SRC_IP,				// CONFIG_STRING[CSI_SRC_IP]			
	CSI_SRC_PORT,			// CONFIG_STRING[CSI_SRC_PORT]			
	CSI_DST_IP,				// CONFIG_STRING[CSI_DST_IP]			
	CSI_DST_PORT,			// CONFIG_STRING[CSI_DST_PORT]			
	CSI_SERIAL_SECTION,		// CONFIG_STRING[CSI_SERIAL_SECTION]	
	CSI_SERIAL_PORT,		// CONFIG_STRING[CSI_SERIAL_PORT]		
	CSI_SERIAL_BAUD_RATE,	// CONFIG_STRING[CSI_SERIAL_BAUD_RATE]
	CSI_SERIAL_DATA_WIDTH,	// CONFIG_STRING[CSI_SERIAL_DATA_WIDTH]
	CSI_SERIAL_STOP_BITS,	// CONFIG_STRING[CSI_SERIAL_STOP_BITS]
	CSI_SERIAL_PARITY_MODE,	// CONFIG_STRING[CSI_SERIAL_PARITY_MODE]
	CSI_END_SECTION,		// CONFIG_STRING[CSI_END_SECTION]		
	CSI_END_CONFIG,			// CONFIG_STRING[CSI_END_CONFIG]
	CONFIG_STRING_MAX
};

//Config 폴더 내 ini파일 명명 규칙에 쓰이는 string 값.
const std::string EQUIPMENT_NAME[EQUIP_ID_ALL] =
{
	"OSD", "MFR", "SONAR", "RCWS", "TACM", "BCU", "CIWS2", "DECOY", "EOTS", "EW2", "IFF", "IRST", "LESM", "NR", "SAAM", "SAM2", "SLM", "SLTS", "SSM", "SSMx", "TRN", "VLA"
}; //"XXX"

//설정파일(*.ini)에 사용되는 필드들의 string 값
const std::string CONFIG_STRING[CONFIG_STRING_MAX] =
{
			"--START SECTION--",  //E_CONFIG_STRING_IDXCSI_START_SECTION
			"INTERFACE_ID=",
			"INTERFACE_TYPE=",
			"INTERFACE_DESCRIPTION=",
			"[ETHERNET]",
			"SRC_IP=",
			"SRC_PORT=",
			"DST_IP=",
			"DST_PORT=",
			"[SERIAL]",
			"SERIAL_PORT=",
			"SERIAL_BAUD_RATE=",
			"SERIAL_DATA_WIDTH=",
			"SERIAL_STOP_BITS=",
			"SERIAL_PARITY_MODE=",
			"-- END SECTION --",
			"------ END CONFIG ------"
};
#pragma pack(pop)